name: Build and Publish

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  DOTNET_VERSION: 8.0.x
  PackageDir: ${{ github.workspace }}/nuget

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET 6.0.402
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.402
      - name: Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Use Xcode version 16
        run: sudo xcode-select -s /Applications/Xcode_16.app/Contents/Developer
      - name: Build iOS bindings
        run: |
          pushd lib/GoogleApisForiOSComponents/source/Google/MobileAds
          dotnet workload restore
          dotnet build -c Release
          popd
      - name: Restore workloads
        run: dotnet workload restore
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
